name: Warn for Invalid Arguments

on:
  workflow_dispatch

jobs:
  run-invalid:
    runs-on: ubuntu-18.04
    steps:
      - name: Write results
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            **Hi There!**
            We're given invalid arguments.
            Check if you're breaking any limitations:
              - You have to follow this command:
                - runsimulation <number: numberOfDoors> <number: numberOfSimulations>
              - 2 < numberOfDoors < 50
              - 0 < numberOfSimulations < 100000
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'smskcm'
          allow-repeats: true