name: Warn for Invalid Arguments

on:
  workflow_dispatch

jobs:
  run-invalid:
    runs-on: ubuntu-18.04
    steps:
      - name: Write results
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            if (split.length === 3 && parseInt(split[1]) < 50 && parseInt(split[2]) < 100000)
            **Hi!**
            We're given invalid arguments.
            Check if you're breaking limitations:
              - You have to follow this command:
                - runsimulation <int: numberOfDoors> <int: numberOfSimulations>
              - numberOfDoors < 50
              - numberOfSimulations < 100000
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'smskcm'
          allow-repeats: true